# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "IT Architect's Blog"
description: > # this means to ignore newlines until "email:"
  Blog on various trends, how-tos, hacks, set-ups, kubernetes, Containers, GitHub Actions, DevOps Tooling and  to the best practices.

email: pypycodes@outlook.com
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Pypycodes'
author: 'Pypycodes'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://pypycodes.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@pypycodes'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname
#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/pypycodes
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/pypycodes
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/pgop
    desc:	Follow on LinkedIn
    share_url:
    share_title:
    share_link:

  - icon:	facebook
    url:	https://facebook.com/pypycodes
    desc:	Follow on Facebook
    share_url:
    share_title:
    share_link:

  # - icon:	instagram
  #   url:	https://instagram.com/pypycodes
  #   desc:	Follow on Instagram
  #   share_url:
  #   share_title:
  #   share_link:

