# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Architect's Diary
email: pypycodes@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Blogs on Technology and IT Architectures
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pypycodes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pypycodes
github_username:  pypycodes
author:
  name: Pypycodes
  twitter: pypycodes
  picture: /assets/images/author.jpg

# Build settings
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
markdown: kramdown
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-algolia
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: /page:num/

lang: en-US
search: true
search_full_content: true
search_provider: algolia
copyright: "All rights reserved - pypycodes"
logo: /assets/images/author.jpg

algolia:
  application_id: A1P29EWZ3T # YOUR_APPLICATION_ID
  index_name: pypycodes.github.io # YOUR_INDEX_NAME
  search_only_api_key: 062a5da1edfa85e862474ae7435545d4 # YOUR_SEARCH_ONLY_API_KEY
  powered_by: true # true (default), false

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
      author:
        name: Pypycodes
        picture: /assets/images/author.jpg
      comments: true
  # # _recipes
  # - scope:
  #     path: "_recipes"
  #     type: recipes
  #   values:
  #     layout: post
  #     read_time: true
